version: '3'
services:
  app:
    image: node:bullseye-slim
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 3001:3001
      - 8787:8787

  prometheus:
    image: prom/prometheus:latest
    command: --config.file=/etc/prometheus/prometheus.yml --no-scrape.adjust-timestamps
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app
